export type Book = {
  id: string;
  title: string;
  languages: string[];
  author: string;
  isbn: string;
};

export const books: Book[] = [
  {
    id: "1",
    title: "O Senhor dos Anéis",
    languages: ["Portuguese", "English"],
    author: "J.R.R. Tolkien",
    isbn: "978-8533615549",
  },
  {
    id: "2",
    title: "1984",
    languages: ["English"],
    author: "George Orwell",
    isbn: "978-0451524935",
  },
  {
    id: "3",
    title: "Dom Casmurro",
    languages: ["Portuguese"],
    author: "Machado de Assis",
    isbn: "978-8503013830",
  },
  {
    id: "4",
    title: "Crime e Castigo",
    languages: ["Portuguese", "Russian"],
    author: "Fiódor Dostoiévski",
    isbn: "978-8537813522",
  },
  {
    id: "5",
    title: "O Pequeno Príncipe",
    languages: ["Portuguese", "French"],
    author: "Antoine de Saint-Exupéry",
    isbn: "978-2070612758",
  },
  {
    id: "6",
    title: "Moby Dick",
    languages: ["English"],
    author: "Herman Melville",
    isbn: "978-1503280786",
  },
  {
    id: "7",
    title: "Orgulho e Preconceito",
    languages: ["Portuguese", "English"],
    author: "Jane Austen",
    isbn: "978-0141439518",
  },
  {
    id: "8",
    title: "Memórias Póstumas de Brás Cubas",
    languages: ["Portuguese"],
    author: "Machado de Assis",
    isbn: "978-8525060530",
  },
  {
    id: "9",
    title: "A Revolução dos Bichos",
    languages: ["Portuguese", "English"],
    author: "George Orwell",
    isbn: "978-8535909553",
  },
  {
    id: "10",
    title: "O Hobbit",
    languages: ["Portuguese", "English"],
    author: "J.R.R. Tolkien",
    isbn: "978-8533613377",
  },
  {
    id: "11",
    title: "Drácula",
    languages: ["English"],
    author: "Bram Stoker",
    isbn: "978-0141439846",
  },
  {
    id: "12",
    title: "Odisseia",
    languages: ["Portuguese", "Greek"],
    author: "Homero",
    isbn: "978-0140268867",
  },
  {
    id: "13",
    title: "Ilíada",
    languages: ["Portuguese", "Greek"],
    author: "Homero",
    isbn: "978-0140275360",
  },
  {
    id: "14",
    title: "Hamlet",
    languages: ["English"],
    author: "William Shakespeare",
    isbn: "978-0521618748",
  },
  {
    id: "15",
    title: "Macbeth",
    languages: ["English"],
    author: "William Shakespeare",
    isbn: "978-0743477109",
  },
  {
    id: "16",
    title: "O Morro dos Ventos Uivantes",
    languages: ["Portuguese", "English"],
    author: "Emily Brontë",
    isbn: "978-0141439556",
  },
  {
    id: "17",
    title: "Os Três Mosqueteiros",
    languages: ["Portuguese", "French"],
    author: "Alexandre Dumas",
    isbn: "978-0140449266",
  },
  {
    id: "18",
    title: "O Conde de Monte Cristo",
    languages: ["Portuguese", "French"],
    author: "Alexandre Dumas",
    isbn: "978-0140449267",
  },
  {
    id: "19",
    title: "A Divina Comédia",
    languages: ["Portuguese", "Italian"],
    author: "Dante Alighieri",
    isbn: "978-0140448955",
  },
  {
    id: "20",
    title: "Fausto",
    languages: ["Portuguese", "German"],
    author: "Johann Wolfgang von Goethe",
    isbn: "978-0140449013",
  },
  {
    id: "21",
    title: "A Metamorfose",
    languages: ["Portuguese", "German"],
    author: "Franz Kafka",
    isbn: "978-8535909409",
  },
  {
    id: "22",
    title: "O Estrangeiro",
    languages: ["Portuguese", "French"],
    author: "Albert Camus",
    isbn: "978-8535909552",
  },
  {
    id: "23",
    title: "Os Miseráveis",
    languages: ["Portuguese", "French"],
    author: "Victor Hugo",
    isbn: "978-2070408503",
  },
  {
    id: "24",
    title: "Guerra e Paz",
    languages: ["Portuguese", "Russian"],
    author: "Liev Tolstói",
    isbn: "978-0140447934",
  },
  {
    id: "25",
    title: "Madame Bovary",
    languages: ["Portuguese", "French"],
    author: "Gustave Flaubert",
    isbn: "978-2070418502",
  },
];
